package conf

import "shared/config"

var VarList = []config.ConfigVar{
	"POSTGRES_USER",
	"POSTGRES_PASSWORD",
	"POSTGRES_DB_NAME",
	"POSTGRES_HOST",
	"POSTGRES_PORT",

	"SERVER_PORT",
	"SERVER_JWT_SECRET",

	"KAFKA_TOPIC_REQ",
	"KAFKA_TOPIC_RES",
	"KAFKA_URL",
	"KAFKA_CONSUMER_GROUP_ID",
}
