services:
  # ==== DB ===
  db:
    image: postgres:17.0-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  # ==== KAFKA ====

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "broker:29092"
    depends_on:
      - broker

  # ==== API ====

  server:
    build:
      context: .
      dockerfile: docker/local/server/Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_JWT_SECRET=${SERVER_JWT_SECRET}
      - KAFKA_TOPIC={KAFKA_TOPIC}
      - KAFKA_URL={KAFKA_URL}
      - KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
    ports:
      - '3000:${SERVER_PORT}'
    volumes:
      - ./server:/go/src/server
      - ./shared:/go/src/shared
    develop:
      watch:
        - action: sync+restart
          path: ./server
          target: /usr/src/app
    # platform: linux/amd64
    depends_on:
      - db

  worker:
    build:
      dockerfile: docker/local/worker/Dockerfile
      context: .
    volumes:
      - ./worker:/go/src/worker
      - ./shared:/go/src/shared
    depends_on:
      - zookeeper
      - server
    platform: linux/amd64
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_JWT_SECRET=${SERVER_JWT_SECRET}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
