package config

type ConfigVar string

const (
	POSTGRES_HOST     ConfigVar = "POSTGRES_HOST"
	POSTGRES_PORT     ConfigVar = "POSTGRES_HOST"
	POSTGRES_USER     ConfigVar = "POSTGRES_USER"
	POSTGRES_PASSWORD ConfigVar = "POSTGRES_PASSWORD"
	POSTGRES_DB_NAME  ConfigVar = "POSTGRES_DB_NAME"

	SERVER_HOST ConfigVar = "SERVER_HOST"
	SERVER_PORT ConfigVar = "SERVER_PORT"
)
