package config

type ConfigVar string

const (
	POSTGRES_HOST     ConfigVar = "POSTGRES_HOST"
	POSTGRES_PORT     ConfigVar = "POSTGRES_PORT"
	POSTGRES_USER     ConfigVar = "POSTGRES_USER"
	POSTGRES_PASSWORD ConfigVar = "POSTGRES_PASSWORD"
	POSTGRES_DB_NAME  ConfigVar = "POSTGRES_DB_NAME"

	SERVER_HOST       ConfigVar = "SERVER_HOST"
	SERVER_PORT       ConfigVar = "SERVER_PORT"
	SERVER_JWT_SECRET ConfigVar = "SERVER_JWT_SECRET"

	KAFKA_TOPIC_REQ         ConfigVar = "KAFKA_TOPIC_REQ"
	KAFKA_TOPIC_RES         ConfigVar = "KAFKA_TOPIC_RES"
	KAFKA_URL               ConfigVar = "KAFKA_URL"
	KAFKA_CONSUMER_GROUP_ID ConfigVar = "KAFKA_CONSUMER_GROUP_ID"
)
