// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type User struct {
	ID        int32
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
