// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/sqlc-dev/pqtype"
)

type Querier interface {
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreatePort(ctx context.Context, arg CreatePortParams) (Port, error)
	CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAddress(ctx context.Context, id int32) (Address, error)
	DeleteScan(ctx context.Context, arg DeleteScanParams) (Scan, error)
	GetAddress(ctx context.Context, id int32) (Address, error)
	GetAddressByEmail(ctx context.Context, ipAddr pqtype.Inet) (Address, error)
	GetPort(ctx context.Context, id int32) (Port, error)
	GetPortsByIpId(ctx context.Context, ipAddrID int32) ([]Port, error)
	GetScan(ctx context.Context, id int32) (Scan, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListScansByUser(ctx context.Context, userID int32) ([]Scan, error)
	Listusers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
